import { Scene } from "./schema";

/**
 * Order here is the order on the site. Every figure on a scene reads its
 * numbers from this file. Items marked TODO are awaiting confirmation and
 * must be resolved before launch; see README.
 */
const raw = [
  {
    index: "02",
    slug: "neuraluna",
    name: "Model Selection",
    org: "Neuraluna AI",
    period: "Summer 2026",
    headline: ["Thirty-two models,", "one wrong default."],
    lede: "Model selection was running on intuition.",
    body: [
      "Model selection was running on intuition. I built a harness that ran 32 models across 8 production agents and scored every one on quality, cost and latency.",
      "Plotted per agent, most of the argument disappeared. A model is only worth defending if it sits on the frontier, the set nothing else beats on every axis at once. Everything underneath is dominated, and one of the dominated ones was in production.",
    ],
    pull: "Swapping it for the frontier model above cut cost by about a third and improved quality and latency at the same time. Not a tradeoff. A model nobody had measured.",
    metrics: [
      { value: "32", label: "models" },
      { value: "8", label: "agents" },
      { value: "−33%", label: "cost", accent: true },
      { value: "6", label: "fixes shipped" },
    ],
    stack: ["Python", "Pandas", "A/B testing", "Pareto analysis"],
    pinned: true,
    entryGrid: "pareto",
    figure: {
      kind: "pareto",
      models: 32,
      agents: 8,
      production: { quality: 0.81, cost: 1.94, p95: 3.2 },
      recommended: { quality: 0.86, cost: 1.3, p95: 2.4 },
      costAxis: [0.08, 0.25, 0.8, 2.4, 6.0],
    },
    illustrative: ["Chart shows one representative agent of eight. Model names withheld."],
    sources: [{ kind: "resume", note: "32 models, 8 agents, ~33% cost reduction, 6 A/B-validated fixes" }],
  },
  {
    index: "03",
    slug: "temple-rag",
    name: "Multilingual RAG",
    org: "Temple University",
    period: "Spring 2025",
    headline: ["A patient who cannot read", "still needs the answer."],
    lede: "A retrieval system for colorectal cancer screening, built so that language and literacy are not conditions of getting an answer.",
    body: [
      "A RAG chatbot grounded in more than a thousand curated medical documents: USPSTF and ACG clinical guidelines, textbook chapters and structured Q and A from colonoscopy literature. Ingestion, embedding, retrieval and serving, deployed as a working application.",
    ],
    pull: "A question can arrive typed, spoken, photographed or uploaded, in any language, and the answer comes back written and read aloud. Every one of those paths exists because a barrier to reading should not be a barrier to screening information.",
    metrics: [
      { value: "1,000+", label: "documents", accent: true },
      { value: "3", label: "faiss indexes" },
      { value: "5", label: "llm configs" },
      { value: "4", label: "input modes" },
    ],
    stack: ["Python", "Streamlit", "LangChain", "FAISS", "Ollama", "Granite 3.3", "LLaVA", "Whisper", "Tesseract", "gTTS"],
    credit: "Advised by Dr Vikas Khurana, gastroenterologist, and Prof. Subodha Kumar, Temple University",
    pinned: false,
    entryGrid: "pipeline",
    figure: {
      kind: "pipeline",
      inputs: ["text", "image + ocr", "pdf", "voice"],
      normalise: ["detect lang", "translate"],
      indexes: ["guidelines", "textbook", "q and a"],
      scorer: "hybrid score",
      model: "granite 3.3",
      gate: "guardian",
      outputs: ["reply", "audio"],
    },
    detail: {
      waysIn: [
        { key: "text", what: "typed query", how: "any language" },
        { key: "image", what: "photo of a leaflet or report", how: "tesseract ocr" },
        { key: "pdf", what: "uploaded document", how: "pdfplumber, pypdf2" },
        { key: "voice", what: "spoken question, live mic", how: "openai whisper" },
      ],
      retrieval: [
        { label: "clinical guidelines", weight: 0.45, source: "uspstf, acg" },
        { label: "textbook content", weight: 0.3, source: "colorectal chapters" },
        { label: "structured q and a", weight: 0.25, source: "colonoscopy literature" },
      ],
      hybridAlpha: 0.5,
      assessed: ["medical accuracy", "hallucination rate", "response coherence"],
      assessedNote:
        "A Granite Guardian pass sits between generation and delivery, flagging and suppressing unsafe responses. Per-configuration scores are not published.",
      keeps: [
        { label: "chat memory", note: "carried into the prompt so follow-up questions work" },
        { label: "session history", note: "resumable, and clearable in one click" },
        { label: "audit log", note: "separate and permanent, kept whatever the user clears" },
      ],
    },
    illustrative: ["Retrieval weights and alpha shown at their defaults.", "Per-configuration evaluation scores are not published."],
    sources: [{ kind: "notes", note: "Project description supplied by the author, September 2026" }],
  },
  {
    index: "04",
    slug: "reqtrace",
    name: "ReqTrace",
    org: "NC State, CSC 510",
    period: "Fall 2025",
    headline: ["Every node points back", "to something someone said."],
    lede: "ReqTrace turns a requirements meeting into a graph you can walk.",
    body: [
      "Audio goes in, Whisper transcribes it, spaCy pulls the entities out, and what comes back is a Neo4j graph of requirements, features, tests and stakeholders joined by depends, validates and owns.",
    ],
    pull: "The part worth building was provenance. Every node keeps a pointer to the sentence that produced it, so you can select a requirement and read the moment it was agreed to instead of trusting a document written afterwards.",
    metrics: [
      { value: "4", label: "node types" },
      { value: "3", label: "edge types" },
      { value: "91%", label: "coverage" },
      { value: "Top 3", label: "in class", accent: true },
    ],
    stack: ["FastAPI", "Whisper", "spaCy", "FAISS", "Neo4j", "React Flow"],
    credit: "Team of five · MIT licensed · archived with a DOI",
    // Holds for part of a viewport so the graph can be explored rather than
    // scrolled past.
    pinned: true,
    entryGrid: "graph",
    figure: {
      kind: "graph",
      nodeTypes: ["stakeholder", "requirement", "feature", "test"],
      edgeTypes: ["owns", "depends", "validates"],
      nodes: 19,
      edges: 24,
      transcript: [
        {
          node: "R-01",
          quote: "Nothing goes out until the upload itself is signed off. That is the gate.",
          at: "00:03:40",
          speaker: "speaker 1",
          session: "session 04",
        },
        {
          node: "R-02",
          quote: "They want to see who asked for it, not just what got built.",
          at: "00:08:05",
          speaker: "speaker 3",
          session: "session 04",
        },
        {
          node: "R-03",
          quote: "If the upload drops halfway we still have to show them the earlier sessions. That one isn't negotiable.",
          at: "00:14:22",
          speaker: "speaker 2",
          session: "session 04",
        },
        {
          node: "R-04",
          quote: "Every change needs a line back to the meeting it came out of, or we are guessing again.",
          at: "00:21:17",
          speaker: "speaker 2",
          session: "session 04",
        },
        {
          node: "R-05",
          quote: "The export has to be readable by someone who was not in the room.",
          at: "00:27:49",
          speaker: "speaker 4",
          session: "session 05",
        },
        {
          node: "R-06",
          quote: "Start from the audio. If we start from notes we have already lost half of it.",
          at: "00:31:02",
          speaker: "speaker 1",
          session: "session 05",
        },
        {
          node: "R-07",
          quote: "Two people disagreeing is a fact about the requirement. Keep both.",
          at: "00:38:55",
          speaker: "speaker 3",
          session: "session 05",
        },
      ],
    },
    illustrative: ["Graph instance, transcript quotes and timestamps are illustrative."],
    sources: [
      { kind: "repository", note: "tiva710/SE_Project_2 README: node and edge types, 91% Codecov, DOI 10.5281/zenodo.17544380", url: "https://github.com/tiva710/SE_Project_2" },
    ],
  },
  {
    index: "05",
    slug: "affordability",
    name: "Affordability",
    org: "NC State",
    period: "2026",
    headline: ["1.1 million posts, three model heads,", "one pass."],
    lede: "Nobody had read this corpus and nobody was going to. My job was to build the thing that made it analysable.",
    body: [
      "A full preprocessing pipeline over 1.1 million social media posts, then three transformer heads in a single pass: a RoBERTa sentiment classifier, a DistilRoBERTa emotion classifier, and BERTopic for unsupervised topic recovery.",
    ],
    pull: "The hard part was never the models. It was making 1.1 million rows survive cleaning, deduplication and language filtering without quietly dropping the population the study was about.",
    metrics: [
      { value: "1.1M", label: "ingested" },
      { value: "912K", label: "after filtering" },
      { value: "3", label: "model heads", accent: true },
      { value: "41", label: "topics" },
    ],
    stack: ["Python", "Pandas", "RoBERTa", "DistilRoBERTa", "BERTopic", "HDBSCAN"],
    credit: "Topic labels and findings withheld pending publication",
    // The section holds itself: its entry state is a sticky block, so a pin on
    // top of that would only add a viewport of dead scroll after it.
    pinned: false,
    entryGrid: "corpus",
    figure: {
      kind: "corpus",
      posts: 1_100_000,
      afterFiltering: 912_441,
      sentimentModel: "cardiffnlp twitter-roberta",
      sentiment: [
        { label: "negative", share: 0.41 },
        { label: "neutral", share: 0.36 },
        { label: "positive", share: 0.23 },
      ],
      emotionModel: "distilroberta, seven classes",
      emotion: [
        { label: "neutral", share: 0.28 },
        { label: "anger", share: 0.19 },
        { label: "sadness", share: 0.17 },
        { label: "fear", share: 0.13 },
        { label: "joy", share: 0.11 },
        { label: "disgust", share: 0.06 },
        { label: "surprise", share: 0.06 },
      ],
      topics: 41,
      topicsShown: 14,
      topicModel: "bertopic over umap",
    },
    illustrative: ["Distributions and cluster map are illustrative. Topic labels withheld."],
    sources: [{ kind: "notes", note: "1.1M+ posts, cardiffnlp/twitter-roberta, j-hartmann emotion, BERTopic" }],
  },
  {
    index: "06",
    slug: "acoustic",
    name: "Acoustic Events",
    org: "NC State",
    period: "Spring 2026",
    headline: ["Trained on ten people. Tested on three it had", "never heard."],
    lede: "Four-class acoustic event classification from chest-microphone recordings. Subject-independent, which is the part of wearable audio that actually breaks.",
    body: [
      "A five-fold log-mel CNN ensembled with LightGBM over PANNs CNN14 embeddings, Viterbi decoding with per-class offset tuning, trained on ten subjects and tested on three the model had never heard.",
    ],
    pull: "0.93 accuracy and 0.78 macro F1 on held-out subjects, with speech at 0.93 F1 and background at 0.96. Non-verbal is under four percent of frames and is the class that needs more data before its numbers mean much.",
    metrics: [
      { value: "672K", label: "frames" },
      { value: "0.78", label: "macro f1" },
      { value: "0.93", label: "accuracy", accent: true },
      { value: "Top 5", label: "in class" },
    ],
    stack: ["PyTorch", "PANNs CNN14", "LightGBM", "log-mel", "Viterbi", "5-fold"],
    pinned: false,
    entryGrid: "spectrogram",
    figure: {
      kind: "spectrogram",
      frames: 672_203,
      classes: [
        { name: "speech", support: 116_416, precision: 0.9, recall: 0.96, f1: 0.93, glyph: "=" },
        { name: "cough", support: 45_231, precision: 0.76, recall: 0.82, f1: 0.79, glyph: "8" },
        { name: "non-verbal", support: 26_331, precision: 0.65, recall: 0.35, f1: 0.46, glyph: "+" },
        { name: "other", support: 484_225, precision: 0.96, recall: 0.96, f1: 0.96, glyph: "\u00b7" },
      ],
      accuracy: 0.93,
      macroF1: 0.78,
      weightedF1: 0.92,
      trainSubjects: 10,
      heldOutSubjects: 3,
    },
    illustrative: ["Spectrogram and frame timeline are illustrative windows."],
    sources: [
      { kind: "report", note: "Classification report: speech 0.90/0.96/0.93, cough 0.76/0.82/0.79, non-verbal 0.65/0.35/0.46, other 0.96/0.96/0.96, n=672,203" },
      { kind: "notes", note: "Ten training subjects, three held out; thirteen in total" },
    ],
  },
  {
    index: "07",
    slug: "skin-cancer",
    name: "Skin Cancer Screening",
    org: "NC State, CSC 542",
    period: "Spring 2026",
    headline: ["Missing a cancer costs more than a", "false alarm."],
    lede: "Binary screening over 10,015 dermatoscopic images. Where we set the threshold was a clinical decision, not an optimisation.",
    body: [
      "Four models over HAM10000: EfficientNet-B3, B5, a multiclass-pretrained B5 and an EVA02 vision transformer, combined by five-pass test-time augmentation and weighted by validation AUC. Focal loss, MixUp and CutMix, and a weighted sampler to handle the 4:1 imbalance.",
    ],
    pull: "We set the operating threshold at 0.40 rather than the 0.50 that maximises F1. That trade costs precision and buys recall, and it caught 275 of 293 malignant cases in the held-out test set.",
    metrics: [
      { value: "0.964", label: "roc-auc", accent: true },
      { value: "93.9%", label: "recall" },
      { value: "18", label: "missed of 293" },
      { value: "10,015", label: "images" },
    ],
    stack: ["PyTorch", "EfficientNet", "EVA02 ViT", "Focal loss", "MixUp / CutMix", "TTA"],
    credit: "Team of three · NC State AI Student Symposium 2026",
    pinned: false,
    entryGrid: "contact-sheet",
    figure: {
      kind: "contactSheet",
      total: 10_015,
      positive: 1_954,
      stages: [
        { label: "logistic regression", rocAuc: 0.756 },
        { label: "efficientnet-b3", rocAuc: 0.931 },
        { label: "efficientnet-b5", rocAuc: 0.933 },
        { label: "b5 + multiclass pretrain", rocAuc: 0.936 },
        { label: "eva02 vit", rocAuc: 0.962 },
        { label: "weighted ensemble", rocAuc: 0.964 },
      ],
      scaleLo: 0.7,
      scaleHi: 0.98,
      testImages: 1_503,
      confusion: {
        benign: { predBenign: 1_025, predMalignant: 185 },
        malignant: { predBenign: 18, predMalignant: 275 },
      },
      threshold: 0.4,
      bestF1Threshold: 0.5,
      f1AtThreshold: 0.73,
      f1AtBestF1: 0.81,
      baseline: {
        label: "logistic regression",
        rocAuc: 0.756,
        recall: 0.891,
        precision: 0.611,
        f1: 0.725,
        accuracy: 0.703,
      },
      rocAuc: 0.964,
      dataset: "HAM10000",
      citation: "HAM10000, Tschandl et al. 2018",
    },
    illustrative: [],
    sources: [
      { kind: "report", note: "Ensemble (weighted TTA): accuracy 0.8649, precision 0.5978, recall 0.9386, F1 0.7304, ROC-AUC 0.9640; confusion 1025/185/18/275" },
      { kind: "poster", note: "AI Student Symposium 2026 poster: AUC progression 0.756 to 0.964, threshold 0.40, 18 missed of 293" },
    ],
  },
] as const;

export const projects: Scene[] = raw.map((p) => Scene.parse(p));

export const projectBySlug = (slug: string): Scene | undefined =>
  projects.find((p) => p.slug === slug);
